// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package http

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"eats/backend/common"
	"eats/backend/common/shared"
	"eats/backend/orders/app"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
	openapi_types "github.com/oapi-codegen/runtime/types"
	"github.com/shopspring/decimal"
)

// Address defines model for Address.
type Address struct {
	// City City of the address
	City string `json:"city"`

	// CountryCode Country code in ISO 3166-1 alpha-2 format
	CountryCode CountryCode `json:"country_code"`

	// Line1 First line of the address
	Line1 string `json:"line1"`

	// Line2 Second line of the address
	Line2 string `json:"line2"`

	// PostalCode Postal code of the address
	PostalCode string `json:"postal_code"`
}

// CountryCode Country code in ISO 3166-1 alpha-2 format
type CountryCode = shared.CountryCode

// Currency Currency code in ISO 4217 format
type Currency = shared.Currency

// CustomerUUID UUID of a customer
type CustomerUUID = app.CustomerUUID

// Decimal defines model for Decimal.
type Decimal = decimal.Decimal

// ErrorDetails defines model for ErrorDetails.
type ErrorDetails struct {
	EntityId   *string `json:"entity_id,omitempty"`
	EntityType *string `json:"entity_type,omitempty"`
	ErrorSlug  string  `json:"error_slug"`
	Message    string  `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Details Detailed error information
	Details []ErrorDetails `json:"details"`

	// Message Human-readable error message
	Message string `json:"message"`

	// Slug Error slug
	Slug string `json:"slug"`
}

// MenuItem defines model for MenuItem.
type MenuItem struct {
	GrossPrice Decimal `json:"gross_price"`

	// Name Item name
	Name string `json:"name"`

	// Ordering Ordering index for display
	Ordering float32 `json:"ordering"`

	// Uuid UUID of a menu item
	Uuid MenuItemUUID `json:"uuid"`
}

// MenuItemUUID UUID of a menu item
type MenuItemUUID = app.RestaurantMenuItemUUID

// OnboardRestaurant defines model for OnboardRestaurant.
type OnboardRestaurant struct {
	Address Address `json:"address"`

	// Currency Currency code in ISO 4217 format
	Currency Currency `json:"currency"`

	// Description Restaurant description
	Description string `json:"description"`

	// MenuItems Menu items for the restaurant
	MenuItems []MenuItem `json:"menu_items"`

	// Name Restaurant name
	Name string `json:"name"`
}

// OperatorUUID UUID of an operator
type OperatorUUID = common.UUID

// RegisterCustomer defines model for RegisterCustomer.
type RegisterCustomer struct {
	Address Address `json:"address"`

	// Email Customer's email address
	Email openapi_types.Email `json:"email"`

	// Name Customer's full name
	Name string `json:"name"`

	// PhoneNumber Customer's phone number
	PhoneNumber string `json:"phone_number"`
}

// RegisterCustomerResponse defines model for RegisterCustomerResponse.
type RegisterCustomerResponse struct {
	// CustomerUuid UUID of a customer
	CustomerUuid CustomerUUID `json:"customer_uuid"`
}

// RestaurantUUID UUID of a restaurant
type RestaurantUUID = app.RestaurantUUID

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// OnboardRestaurantParams defines parameters for OnboardRestaurant.
type OnboardRestaurantParams struct {
	OperatorUUID OperatorUUID `json:"Operator-UUID"`
}

// RegisterCustomerJSONRequestBody defines body for RegisterCustomer for application/json ContentType.
type RegisterCustomerJSONRequestBody = RegisterCustomer

// OnboardRestaurantJSONRequestBody defines body for OnboardRestaurant for application/json ContentType.
type OnboardRestaurantJSONRequestBody = OnboardRestaurant

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Register a new customer
	// (POST /orders/register-customer)
	RegisterCustomer(ctx echo.Context) error
	// Onboard or replace a restaurant with full details
	// (PUT /orders/restaurant/onboard/{restaurant_uuid})
	OnboardRestaurant(ctx echo.Context, restaurantUuid RestaurantUUID, params OnboardRestaurantParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// RegisterCustomer converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterCustomer(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RegisterCustomer(ctx)
	return err
}

// OnboardRestaurant converts echo context to params.
func (w *ServerInterfaceWrapper) OnboardRestaurant(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "restaurant_uuid" -------------
	var restaurantUuid RestaurantUUID

	err = runtime.BindStyledParameterWithOptions("simple", "restaurant_uuid", ctx.Param("restaurant_uuid"), &restaurantUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter restaurant_uuid: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params OnboardRestaurantParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Operator-UUID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Operator-UUID")]; found {
		var OperatorUUID OperatorUUID
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Operator-UUID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Operator-UUID", valueList[0], &OperatorUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Operator-UUID: %s", err))
		}

		params.OperatorUUID = OperatorUUID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Operator-UUID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.OnboardRestaurant(ctx, restaurantUuid, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/orders/register-customer", wrapper.RegisterCustomer)
	router.PUT(baseURL+"/orders/restaurant/onboard/:restaurant_uuid", wrapper.OnboardRestaurant)

}

type BadRequestJSONResponse ErrorResponse

type ForbiddenJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type RegisterCustomerRequestObject struct {
	Body *RegisterCustomerJSONRequestBody
}

type RegisterCustomerResponseObject interface {
	VisitRegisterCustomerResponse(w http.ResponseWriter) error
}

type RegisterCustomer201JSONResponse RegisterCustomerResponse

func (response RegisterCustomer201JSONResponse) VisitRegisterCustomerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type RegisterCustomer400JSONResponse struct{ BadRequestJSONResponse }

func (response RegisterCustomer400JSONResponse) VisitRegisterCustomerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RegisterCustomer409JSONResponse ErrorResponse

func (response RegisterCustomer409JSONResponse) VisitRegisterCustomerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type OnboardRestaurantRequestObject struct {
	RestaurantUuid RestaurantUUID `json:"restaurant_uuid"`
	Params         OnboardRestaurantParams
	Body           *OnboardRestaurantJSONRequestBody
}

type OnboardRestaurantResponseObject interface {
	VisitOnboardRestaurantResponse(w http.ResponseWriter) error
}

type OnboardRestaurant204Response struct {
}

func (response OnboardRestaurant204Response) VisitOnboardRestaurantResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type OnboardRestaurant400JSONResponse struct{ BadRequestJSONResponse }

func (response OnboardRestaurant400JSONResponse) VisitOnboardRestaurantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type OnboardRestaurant401JSONResponse struct{ UnauthorizedJSONResponse }

func (response OnboardRestaurant401JSONResponse) VisitOnboardRestaurantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type OnboardRestaurant403JSONResponse struct{ ForbiddenJSONResponse }

func (response OnboardRestaurant403JSONResponse) VisitOnboardRestaurantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Register a new customer
	// (POST /orders/register-customer)
	RegisterCustomer(ctx context.Context, request RegisterCustomerRequestObject) (RegisterCustomerResponseObject, error)
	// Onboard or replace a restaurant with full details
	// (PUT /orders/restaurant/onboard/{restaurant_uuid})
	OnboardRestaurant(ctx context.Context, request OnboardRestaurantRequestObject) (OnboardRestaurantResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// RegisterCustomer operation middleware
func (sh *strictHandler) RegisterCustomer(ctx echo.Context) error {
	var request RegisterCustomerRequestObject

	var body RegisterCustomerJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterCustomer(ctx.Request().Context(), request.(RegisterCustomerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterCustomer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RegisterCustomerResponseObject); ok {
		return validResponse.VisitRegisterCustomerResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// OnboardRestaurant operation middleware
func (sh *strictHandler) OnboardRestaurant(ctx echo.Context, restaurantUuid RestaurantUUID, params OnboardRestaurantParams) error {
	var request OnboardRestaurantRequestObject

	request.RestaurantUuid = restaurantUuid
	request.Params = params

	var body OnboardRestaurantJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.OnboardRestaurant(ctx.Request().Context(), request.(OnboardRestaurantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "OnboardRestaurant")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(OnboardRestaurantResponseObject); ok {
		return validResponse.VisitOnboardRestaurantResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
