// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbmodels

import (
	"eats/backend/common/shared"
	"eats/backend/orders/app"
	"github.com/shopspring/decimal"
)

type OrdersCustomer struct {
	CustomerUuid app.CustomerUUID
	Name         string
	Email        string
	Address      shared.Address
	PhoneNumber  string
}

type OrdersRestaurant struct {
	RestaurantUuid app.RestaurantUUID
	Name           string
	Description    string
	Address        shared.Address
	Currency       shared.Currency
}

type OrdersRestaurantMenuItem struct {
	RestaurantMenuItemUuid app.RestaurantMenuItemUUID
	RestaurantUuid         app.RestaurantUUID
	Name                   string
	GrossPrice             decimal.Decimal
	Ordering               float64
	IsArchived             bool
}
